/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingPageRouteImport } from './routes/trackingPage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as Search_assistanceRouteImport } from './routes/search_assistance'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrackingPageRoute = TrackingPageRouteImport.update({
  id: '/trackingPage',
  path: '/trackingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const Search_assistanceRoute = Search_assistanceRouteImport.update({
  id: '/search_assistance',
  path: '/search_assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/search_assistance': typeof Search_assistanceRoute
  '/settings': typeof SettingsRoute
  '/trackingPage': typeof TrackingPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/search_assistance': typeof Search_assistanceRoute
  '/settings': typeof SettingsRoute
  '/trackingPage': typeof TrackingPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/search_assistance': typeof Search_assistanceRoute
  '/settings': typeof SettingsRoute
  '/trackingPage': typeof TrackingPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/search_assistance'
    | '/settings'
    | '/trackingPage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/search_assistance'
    | '/settings'
    | '/trackingPage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/search_assistance'
    | '/settings'
    | '/trackingPage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  Search_assistanceRoute: typeof Search_assistanceRoute
  SettingsRoute: typeof SettingsRoute
  TrackingPageRoute: typeof TrackingPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trackingPage': {
      id: '/trackingPage'
      path: '/trackingPage'
      fullPath: '/trackingPage'
      preLoaderRoute: typeof TrackingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search_assistance': {
      id: '/search_assistance'
      path: '/search_assistance'
      fullPath: '/search_assistance'
      preLoaderRoute: typeof Search_assistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  Search_assistanceRoute: Search_assistanceRoute,
  SettingsRoute: SettingsRoute,
  TrackingPageRoute: TrackingPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
